command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: DATABRICKS_TOKEN
    value: "{{secrets/brickchat-secrets/databricks-token}}"
  - name: DATABRICKS_BASE_URL
    value: "https://adb-984752964297111.11.azuredatabricks.net/serving-endpoints"
  - name: DATABRICKS_MODEL
    value: "ka-4b190238-endpoint"
  - name: DEEPGRAM_API_KEY
    value: "{{secrets/brickchat-secrets/deepgram-api-key}}"
  - name: REPLICATE_API_TOKEN
    value: "{{secrets/brickchat-secrets/replicate-api-token}}"